# Generated by Django 3.0.2 on 2020-03-18 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_register', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='code',
            old_name='stud_code',
            new_name='department_title',
        ),
    ]
